<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <IsPackable>false</IsPackable>
        <IsTestProject>true</IsTestProject>
        <OutputType>Exe</OutputType>
        <UserSecretsId>6def17cb-5c8e-4c55-8368-caa850c8d306</UserSecretsId>
    </PropertyGroup>

    <ItemGroup>
        <None Remove="appsettings.json" />
    </ItemGroup>

    <ItemGroup>
        <Content Include="appsettings.json">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </Content>
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="FluentAssertions" />
        <PackageReference Include="Microsoft.Extensions.Configuration" />
        <PackageReference Include="Microsoft.Extensions.Configuration.EnvironmentVariables" />
        <PackageReference Include="Microsoft.Extensions.Configuration.Json" />
        <PackageReference Include="Microsoft.Extensions.Configuration.UserSecrets" />
        <PackageReference Include="Moq" />
        <PackageReference Include="Moq.AutoMock" />
        <PackageReference Include="xunit.v3" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\src\Wayd.Integrations.AzureDevOps\Wayd.Integrations.AzureDevOps.csproj" />
    </ItemGroup>

</Project>
