<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <IsTestProject>true</IsTestProject>
        <OutputType>Exe</OutputType>
        <IsPackable>false</IsPackable>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="FluentAssertions" />
        <PackageReference Include="NodaTime.Serialization.SystemTextJson" />
        <PackageReference Include="xunit.v3" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\..\src\Wayd.Common.Domain\Wayd.Common.Domain.csproj" />
      <ProjectReference Include="..\Wayd.Tests.Shared\Wayd.Tests.Shared.csproj" />
    </ItemGroup>

</Project>
