<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <IsPackable>false</IsPackable>
        <IsTestProject>true</IsTestProject>
        <OutputType>Exe</OutputType>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="FluentAssertions" />
        <PackageReference Include="Moq" />
        <PackageReference Include="Moq.AutoMock" />
        <PackageReference Include="NodaTime.Testing" />
        <PackageReference Include="xunit.v3" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\..\..\Wayd.Common\src\Wayd.Common.Domain\Wayd.Common.Domain.csproj" />
        <ProjectReference Include="..\..\..\..\Wayd.Common\tests\Wayd.Tests.Shared\Wayd.Tests.Shared.csproj" />
        <ProjectReference Include="..\..\..\..\Wayd.Common\tests\Wayd.Common.Domain.Tests\Wayd.Common.Domain.Tests.csproj" />
        <ProjectReference Include="..\Wayd.Organization.Domain.Tests\Wayd.Organization.Domain.Tests.csproj" />
        <ProjectReference Include="..\..\src\Wayd.Organization.Application\Wayd.Organization.Application.csproj" />
    </ItemGroup>

    <ItemGroup>
        <Using Include="Xunit" />
    </ItemGroup>

</Project>