using Ardalis.GuardClauses;
using NodaTime;
using Wayd.Common.Domain.Data;
using Wayd.Common.Domain.Events;

namespace Wayd.Common.Domain.Activities;

/// <summary>
/// An immutable, append-only record of a domain business event.
/// Captures what occurred, on what aggregate, by whom, and when.
/// </summary>
public sealed class ActivityLogEntry : BaseEntity<long>
{
    private readonly List<ActivityLogRelatedAggregate> _relatedAggregates = [];

    private ActivityLogEntry() { }

    public ActivityLogEntry(
        Guid eventId,
        string eventType,
        ActivityCategory category,
        string domainArea,
        string aggregateType,
        Guid aggregateId,
        EventActor actor,
        Instant timestamp,
        int ordinal,
        string? correlationId,
        string payload,
        string? summary = null,
        string eventVersion = "1.0",
        IEnumerable<AggregateReference>? relatedAggregates = null)
    {
        EventId = Guard.Against.Default(eventId, nameof(eventId));
        EventType = Guard.Against.NullOrWhiteSpace(eventType, nameof(eventType)).Trim();
        Category = Guard.Against.EnumOutOfRange(category, nameof(category));
        EventVersion = string.IsNullOrWhiteSpace(eventVersion) ? "1.0" : eventVersion.Trim();
        DomainArea = Guard.Against.NullOrWhiteSpace(domainArea, nameof(domainArea)).Trim();
        AggregateType = Guard.Against.NullOrWhiteSpace(aggregateType, nameof(aggregateType)).Trim();
        AggregateId = Guard.Against.Default(aggregateId, nameof(aggregateId));

        Guard.Against.Null(actor, nameof(actor));
        ActorKind = actor.Kind;
        UserId = actor.UserId;
        EmployeeId = actor.EmployeeId;

        Timestamp = timestamp;
        Ordinal = Guard.Against.Negative(ordinal, nameof(ordinal));
        CorrelationId = string.IsNullOrWhiteSpace(correlationId) ? null : correlationId.Trim();
        Payload = Guard.Against.Null(payload, nameof(payload));
        Summary = string.IsNullOrWhiteSpace(summary) ? null : summary.Trim();

        foreach (var related in relatedAggregates ?? [])
        {
            var reference = new ActivityLogRelatedAggregate(
                Guard.Against.NullOrWhiteSpace(related.AggregateType, nameof(relatedAggregates)).Trim(),
                Guard.Against.Default(related.AggregateId, nameof(relatedAggregates)));

            // Types compare ignoring case because the database does: two casings of one record are one key in the
            // related table, and would fail its insert after the change they record was already committed.
            if (IsSameRecord(reference.AggregateType, reference.AggregateId, AggregateType, AggregateId)
                || _relatedAggregates.Any(r => IsSameRecord(r.AggregateType, r.AggregateId, reference.AggregateType, reference.AggregateId)))
            {
                continue;
            }

            _relatedAggregates.Add(reference);
        }
    }

    private static bool IsSameRecord(string type, Guid id, string otherType, Guid otherId) =>
        id == otherId && string.Equals(type, otherType, StringComparison.OrdinalIgnoreCase);

    /// <summary>The id of the domain event this entry records.</summary>
    /// <remarks>
    /// The deduplication identity, and the reason this is not just another column: an aggregate that writes a
    /// durable record and an event about the same occurrence gives the event that record's id, so a backfill
    /// replaying old records produces the same value and collides instead of inserting a second copy. The
    /// unique index is what enforces that — it used to be the primary key, and the guarantee moved with the
    /// name rather than being given up.
    /// </remarks>
    public Guid EventId { get; private init; }

    /// <summary>Where this entry sits among the entries written by the same unit of work.</summary>
    /// <remarks>
    /// <para>
    /// The ordering identity, as <see cref="EventId"/> is the deduplication identity. The events of
    /// one command are stamped microseconds apart where each domain call reads the clock, and share a
    /// <see cref="Timestamp"/> exactly where the caller reads it once for the batch — an import or a sync. So
    /// timestamp alone is not a sort key: tied rows come back in whatever order the database chooses, which
    /// lets <c>Skip</c>/<c>Take</c> repeat an entry on one page and drop it from the next. Reads order by
    /// <see cref="Timestamp"/>, then this, then <c>Id</c>.
    /// </para>
    /// <para>
    /// Counted by the caller rather than generated by the database. EF sorts the inserts of a save by primary
    /// key, and the key here is a Guid, so the order rows reach the table is unrelated to the order the events
    /// were raised in — a database-assigned number records that shuffle faithfully and is therefore useless.
    /// </para>
    /// <para>
    /// Only ever compared within one <see cref="Timestamp"/>, so it need not be unique and restarts per unit of
    /// work. Two commands that collide on an instant fall through to <c>Id</c>, which is arbitrary but settled:
    /// what paging needs is a tiebreak that answers the same way twice, not a meaningful one.
    /// </para>
    /// </remarks>
    public int Ordinal { get; private init; }

    /// <summary>The runtime type name of the raised domain event.</summary>
    public string EventType { get; private init; } = default!;

    /// <summary>What kind of occurrence the event records, as its type declares it.</summary>
    /// <remarks>
    /// Recorded rather than derived from <see cref="EventType"/> when read, so the Activity section never has
    /// to know any module's vocabulary, and an entry whose type no longer exists still has one.
    /// </remarks>
    public ActivityCategory Category { get; private init; }

    /// <summary>The schema version of the event (e.g. "1.0").</summary>
    public string EventVersion { get; private init; } = "1.0";

    /// <summary>The bounded context domain area (e.g. "Ppm", "Organization", "Planning", "ProductManagement", "Work").</summary>
    public string DomainArea { get; private init; } = default!;

    /// <summary>The aggregate entity type (e.g. "Project", "Team", "Product", "Version").</summary>
    public string AggregateType { get; private init; } = default!;

    /// <summary>The identifier of the target entity.</summary>
    public Guid AggregateId { get; private init; }

    /// <summary>
    /// Other records this entry concerns, whose Activity sections list it alongside their own entries.
    /// </summary>
    /// <remarks>
    /// Never includes the entry's own aggregate. Not loaded unless included: reading a record's activity
    /// matches on these rows in the query and never needs them materialized.
    /// </remarks>
    public IReadOnlyCollection<ActivityLogRelatedAggregate> RelatedAggregates => _relatedAggregates.AsReadOnly();

    /// <summary>The mechanism that performed the change.</summary>
    public EventActorKind ActorKind { get; private init; }

    /// <summary>The account that originated the change, where there is one.</summary>
    public string? UserId { get; private init; }

    /// <summary>The employee behind the change, where there is one.</summary>
    public Guid? EmployeeId { get; private init; }

    /// <summary>The employee navigation entity.</summary>
    public Wayd.Common.Domain.Employees.Employee? Employee { get; private init; }

    /// <summary>When the event occurred in the domain.</summary>
    public Instant Timestamp { get; private init; }

    /// <summary>Ties this event back to the request or background operation that caused it.</summary>
    public string? CorrelationId { get; private init; }

    /// <summary>The serialized JSON representation of the domain event payload.</summary>
    public string Payload { get; private init; } = default!;

    /// <summary>A human-readable summary of the event.</summary>
    public string? Summary { get; private init; }
}

