using Ardalis.GuardClauses;
using NodaTime;
using Wayd.Common.Domain.Data;

namespace Wayd.Common.Domain.Activities;

/// <summary>
/// An immutable, append-only record of a domain business event.
/// Captures what occurred, on what aggregate, by whom, and when.
/// </summary>
public sealed class ActivityLogEntry : BaseEntity
{
    private ActivityLogEntry() { }

    public ActivityLogEntry(
        Guid id,
        string eventType,
        string domainArea,
        string aggregateType,
        Guid aggregateId,
        EventActor actor,
        Instant timestamp,
        int ordinal,
        string? correlationId,
        string payload,
        string? summary = null,
        string eventVersion = "1.0")
    {
        Id = Guard.Against.Default(id, nameof(id));
        EventType = Guard.Against.NullOrWhiteSpace(eventType, nameof(eventType)).Trim();
        EventVersion = string.IsNullOrWhiteSpace(eventVersion) ? "1.0" : eventVersion.Trim();
        DomainArea = Guard.Against.NullOrWhiteSpace(domainArea, nameof(domainArea)).Trim();
        AggregateType = Guard.Against.NullOrWhiteSpace(aggregateType, nameof(aggregateType)).Trim();
        AggregateId = Guard.Against.Default(aggregateId, nameof(aggregateId));

        Guard.Against.Null(actor, nameof(actor));
        ActorKind = actor.Kind;
        UserId = actor.UserId;
        EmployeeId = actor.EmployeeId;

        Timestamp = timestamp;
        Ordinal = Guard.Against.Negative(ordinal, nameof(ordinal));
        CorrelationId = string.IsNullOrWhiteSpace(correlationId) ? null : correlationId.Trim();
        Payload = Guard.Against.Null(payload, nameof(payload));
        Summary = string.IsNullOrWhiteSpace(summary) ? null : summary.Trim();
    }

    /// <summary>Where this entry sits among the entries written by the same unit of work.</summary>
    /// <remarks>
    /// <para>
    /// The ordering identity, as <see cref="BaseEntity{TId}.Id"/> is the deduplication identity. The events of
    /// one command are stamped microseconds apart where each domain call reads the clock, and share a
    /// <see cref="Timestamp"/> exactly where the caller reads it once for the batch — an import or a sync. So
    /// timestamp alone is not a sort key: tied rows come back in whatever order the database chooses, which
    /// lets <c>Skip</c>/<c>Take</c> repeat an entry on one page and drop it from the next. Reads order by
    /// <see cref="Timestamp"/>, then this, then <c>Id</c>.
    /// </para>
    /// <para>
    /// Counted by the caller rather than generated by the database. EF sorts the inserts of a save by primary
    /// key, and the key here is a Guid, so the order rows reach the table is unrelated to the order the events
    /// were raised in — a database-assigned number records that shuffle faithfully and is therefore useless.
    /// </para>
    /// <para>
    /// Only ever compared within one <see cref="Timestamp"/>, so it need not be unique and restarts per unit of
    /// work. Two commands that collide on an instant fall through to <c>Id</c>, which is arbitrary but settled:
    /// what paging needs is a tiebreak that answers the same way twice, not a meaningful one.
    /// </para>
    /// </remarks>
    public int Ordinal { get; private init; }

    /// <summary>The runtime type name of the raised domain event.</summary>
    public string EventType { get; private init; } = default!;

    /// <summary>The schema version of the event (e.g. "1.0").</summary>
    public string EventVersion { get; private init; } = "1.0";

    /// <summary>The bounded context domain area (e.g. "Ppm", "Organization", "Planning", "ProductManagement", "Work").</summary>
    public string DomainArea { get; private init; } = default!;

    /// <summary>The aggregate entity type (e.g. "Project", "Team", "Product", "Version").</summary>
    public string AggregateType { get; private init; } = default!;

    /// <summary>The identifier of the target entity.</summary>
    public Guid AggregateId { get; private init; }

    /// <summary>The mechanism that performed the change.</summary>
    public EventActorKind ActorKind { get; private init; }

    /// <summary>The account that originated the change, where there is one.</summary>
    public string? UserId { get; private init; }

    /// <summary>The employee behind the change, where there is one.</summary>
    public Guid? EmployeeId { get; private init; }

    /// <summary>The employee navigation entity.</summary>
    public Wayd.Common.Domain.Employees.Employee? Employee { get; private init; }

    /// <summary>When the event occurred in the domain.</summary>
    public Instant Timestamp { get; private init; }

    /// <summary>Ties this event back to the request or background operation that caused it.</summary>
    public string? CorrelationId { get; private init; }

    /// <summary>The serialized JSON representation of the domain event payload.</summary>
    public string Payload { get; private init; } = default!;

    /// <summary>A human-readable summary of the event.</summary>
    public string? Summary { get; private init; }
}

