<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <IsTestProject>true</IsTestProject>
    <OutputType>Exe</OutputType>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="FluentAssertions" />
    <PackageReference Include="NodaTime.Testing" />
    <PackageReference Include="xunit.v3" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\..\Wayd.Common\tests\Wayd.Tests.Shared\Wayd.Tests.Shared.csproj" />
    <ProjectReference Include="..\..\src\Wayd.Organization.Domain\Wayd.Organization.Domain.csproj" />
    <ProjectReference Include="..\Wayd.Organization.TestData\Wayd.Organization.TestData.csproj" />
  </ItemGroup>

</Project>
