/**
 * Build-time code generator: reads every CSV import out of the API's OpenAPI
 * document and writes src/generated/import-formats.ts.
 *
 * Run via: tsx scripts/generate-import-formats.ts  (invoked by `npm run build`,
 * before the Zod schemas, which are built from tool definitions that read it)
 *
 * The document is the one the API's Debug build commits, so the formats match
 * the API this package is built against. Each import endpoint carries an
 * `x-wayd-import` extension naming its import key and the row schema of every
 * file it takes; each row property carries `x-csv-column`, the header as the
 * file spells it, and `x-csv-values` where the cell names one of a fixed set.
 * The React client's scripts/import-templates.mjs reads the same extensions for
 * the Settings → Imports dialog.
 */
import { readFileSync, writeFileSync, mkdirSync } from 'fs';
import { fileURLToPath } from 'url';
import { dirname, join } from 'path';
import type { ImportColumn, ImportFormat } from '../src/types.js';

const __dirname = dirname(fileURLToPath(import.meta.url));
const specPath = join(__dirname, '../../Wayd.Web.Api/wwwroot/api/v1/specification.json');
const outDir = join(__dirname, '../src/generated');
const outFile = join(outDir, 'import-formats.ts');

type Schema = Record<string, any>;

const spec = JSON.parse(readFileSync(specPath, 'utf8'));
const schemas: Record<string, Schema> = spec.components.schemas;

const resolve = (schema: Schema): Schema =>
    schema.$ref ? schemas[schema.$ref.replace('#/components/schemas/', '')]! : schema;

// XML doc comments keep their source line breaks.
const flatten = (text: string | undefined) => text?.replace(/\s+/g, ' ').trim() || undefined;

function columnType(property: Schema): ImportColumn['type'] {
    const actual = property.oneOf?.[0] ?? property.allOf?.[0] ?? property;
    switch (actual.format) {
        case 'guid':
        case 'uuid':
            return 'id';
        case 'date':
            return 'date';
        case 'date-time':
            return 'timestamp';
    }
    switch (actual.type) {
        case 'integer':
        case 'number':
        case 'boolean':
            return actual.type;
        default:
            return 'text';
    }
}

function buildColumns(schemaName: string): ImportColumn[] {
    const schema = schemas[schemaName];
    if (!schema) throw new Error(`The OpenAPI document has no schema named '${schemaName}'.`);

    const required = new Set<string>(schema.required ?? []);

    return Object.entries<Schema>(schema.properties ?? {}).map(([jsonName, raw]) => {
        const property = resolve(raw);
        const name = raw['x-csv-column'] ?? property['x-csv-column'];
        if (!name) {
            throw new Error(`${schemaName}.${jsonName} has no x-csv-column; the API's CsvImportOperationProcessor did not run over it.`);
        }

        const column: ImportColumn = { name, type: columnType(raw), required: required.has(jsonName) };
        const description = flatten(raw.description ?? property.description);
        if (description) column.description = description;
        if (raw['x-csv-values']?.length) column.values = raw['x-csv-values'];
        if (raw.maxLength) column.maxLength = raw.maxLength;
        return column;
    });
}

const formats: Record<string, ImportFormat> = {};

for (const [path, pathItem] of Object.entries<Schema>(spec.paths)) {
    for (const operation of Object.values<Schema>(pathItem)) {
        const extension = operation?.['x-wayd-import'];
        if (!extension) continue;

        if (formats[extension.key]) throw new Error(`Two endpoints declare the import '${extension.key}'.`);

        const format: ImportFormat = {
            path,
            files: extension.files.map((file: Schema) => ({
                field: file.field,
                ...(file.label && { label: file.label }),
                required: file.required,
                columns: buildColumns(file.schema),
            })),
        };
        const description = flatten(operation.description);
        if (description) format.description = description;

        formats[extension.key] = format;
    }
}

if (Object.keys(formats).length === 0) {
    throw new Error(`No x-wayd-import operations found in ${specPath}.`);
}

const sorted = Object.fromEntries(Object.entries(formats).sort(([a], [b]) => a.localeCompare(b)));

mkdirSync(outDir, { recursive: true });
writeFileSync(outFile, [
    '// AUTO-GENERATED — do not edit by hand. Regenerated by `npm run build` from the API\'s OpenAPI document.',
    "import type { ImportFormat } from '../types.js';",
    '',
    `export const importFormats: Record<string, ImportFormat> = ${JSON.stringify(sorted, null, 2)};`,
    '',
].join('\n'));
console.error(`Generated ${Object.keys(sorted).length} import formats → ${outFile}`);
