// Generated by scripts/generate-import-templates.mjs from the API's OpenAPI document. Do not edit:
// change the import's row class or its [CsvValues] attributes, rebuild the API, and regenerate.
import type { ImportTemplate } from './import-template'

export const importTemplates = {
  employees: {
    files: [
      {
        field: 'file',
        required: true,
        columns: [
          {
            name: 'ImportId',
            type: 'text',
            required: false,
            description:
              "The caller's own key for this row, unique within the file (case-insensitively). Results are reported against it, and it is how a row is identified without depending on a display name. Falls back to the row's position when the column is absent, so a hand-authored file still works.",
          },
          {
            name: 'EmployeeNumber',
            type: 'text',
            required: true,
            maxLength: 256,
          },
          {
            name: 'FirstName',
            type: 'text',
            required: true,
            maxLength: 100,
          },
          {
            name: 'MiddleName',
            type: 'text',
            required: false,
            maxLength: 100,
          },
          {
            name: 'LastName',
            type: 'text',
            required: true,
            maxLength: 100,
          },
          {
            name: 'Email',
            type: 'text',
            required: true,
            maxLength: 256,
          },
          {
            name: 'HireDate',
            type: 'timestamp',
            required: false,
          },
          {
            name: 'JobTitle',
            type: 'text',
            required: false,
            maxLength: 256,
          },
          {
            name: 'Department',
            type: 'text',
            required: false,
            maxLength: 256,
          },
          {
            name: 'OfficeLocation',
            type: 'text',
            required: false,
            maxLength: 256,
          },
          {
            name: 'ManagerNumber',
            type: 'text',
            required: false,
          },
          {
            name: 'IsActive',
            type: 'boolean',
            required: true,
            description:
              'Whether the employee is currently active. Defaults to true when the column is absent.',
          },
          {
            name: 'EmployeeType',
            type: 'text',
            required: false,
            description:
              'The worker type (e.g. Employee, Contractor, Intern), mirroring the HRIS descriptor. Free-form.',
            maxLength: 256,
          },
          {
            name: 'AdditionalEmails',
            type: 'text',
            required: false,
            description:
              'Further work addresses for this person, semicolon-separated. Email stays the primary; these are additional addresses the person is known by in other systems — typically ones left behind by a domain or tenant move. Home and personal addresses do not belong here.',
          },
        ],
      },
    ],
  },
  'planning.planning-interval-objectives': {
    description:
      'Each row names the planning interval it belongs to in PlanningIntervalId, so one file can cover many planning intervals.',
    files: [
      {
        field: 'file',
        required: true,
        columns: [
          {
            name: 'ImportId',
            type: 'text',
            required: false,
            description:
              "The caller's own key for this row, unique within the file (case-insensitively). Results are reported against it. Falls back to the row's position when the column is absent, so a hand-authored file still works.",
          },
          {
            name: 'PlanningIntervalId',
            type: 'id',
            required: true,
          },
          {
            name: 'TeamId',
            type: 'id',
            required: true,
          },
          {
            name: 'Name',
            type: 'text',
            required: true,
            maxLength: 256,
          },
          {
            name: 'Description',
            type: 'text',
            required: false,
            maxLength: 1024,
          },
          {
            name: 'StatusId',
            type: 'integer',
            required: true,
          },
          {
            name: 'Progress',
            type: 'number',
            required: true,
          },
          {
            name: 'StartDate',
            type: 'date',
            required: false,
          },
          {
            name: 'TargetDate',
            type: 'date',
            required: false,
          },
          {
            name: 'IsStretch',
            type: 'boolean',
            required: true,
          },
          {
            name: 'ClosedDateUtc',
            type: 'timestamp',
            required: false,
          },
          {
            name: 'Order',
            type: 'integer',
            required: false,
          },
        ],
      },
    ],
  },
  'planning.planning-intervals': {
    description:
      'One row is one planning interval, with the teams that ran it in a semicolon-separated TeamIds column. Iterations are generated from IterationWeeks and IterationPrefix; there is no column for them. Creates only — a row whose Name is already taken is rejected, so TeamIds never replaces an existing roster, and a blank TeamIds simply leaves the new interval with no teams.',
    files: [
      {
        field: 'file',
        required: true,
        columns: [
          {
            name: 'ImportId',
            type: 'text',
            required: false,
            description:
              "The caller's own key for this row, unique within the file (case-insensitively). Results are reported against it. Falls back to the row's position when the column is absent, so a hand-authored file still works.",
          },
          {
            name: 'Name',
            type: 'text',
            required: true,
            maxLength: 128,
          },
          {
            name: 'Description',
            type: 'text',
            required: false,
            maxLength: 2048,
          },
          {
            name: 'Start',
            type: 'date',
            required: true,
            description:
              'The dates the interval ran over. Its iterations are generated inside this range.',
          },
          {
            name: 'End',
            type: 'date',
            required: true,
          },
          {
            name: 'IterationWeeks',
            type: 'integer',
            required: true,
            description:
              "The cadence the interval's iterations are generated from. There is no column for the iterations themselves: an interval whose real history had irregular lengths or names is corrected afterwards on its own dates screen.",
          },
          {
            name: 'IterationPrefix',
            type: 'text',
            required: false,
            description:
              "Prefixes each generated iteration's name, which is otherwise just its sequence number — so iterations from different intervals stay tellable apart.",
            maxLength: 32,
          },
          {
            name: 'TeamIds',
            type: 'text',
            required: false,
            description:
              'Semicolon-separated ids of the teams that ran the interval. Blank leaves the new interval with no teams; nothing is ever replaced, since this import only creates.',
          },
        ],
      },
    ],
  },
  'planning.risks': {
    files: [
      {
        field: 'file',
        required: true,
        columns: [
          {
            name: 'ImportId',
            type: 'text',
            required: false,
            description:
              "The caller's own key for this row, unique within the file (case-insensitively). Results are reported against it. Falls back to the row's position when the column is absent, so a hand-authored file still works.",
          },
          {
            name: 'TeamId',
            type: 'id',
            required: true,
          },
          {
            name: 'Summary',
            type: 'text',
            required: true,
            maxLength: 256,
          },
          {
            name: 'Description',
            type: 'text',
            required: false,
            maxLength: 1024,
          },
          {
            name: 'ReportedOnUtc',
            type: 'timestamp',
            required: true,
          },
          {
            name: 'ReportedById',
            type: 'id',
            required: true,
          },
          {
            name: 'StatusId',
            type: 'integer',
            required: true,
          },
          {
            name: 'CategoryId',
            type: 'integer',
            required: true,
          },
          {
            name: 'ImpactId',
            type: 'integer',
            required: true,
          },
          {
            name: 'LikelihoodId',
            type: 'integer',
            required: true,
          },
          {
            name: 'AssigneeId',
            type: 'id',
            required: false,
          },
          {
            name: 'FollowUpDate',
            type: 'date',
            required: false,
          },
          {
            name: 'Response',
            type: 'text',
            required: false,
            maxLength: 1024,
          },
          {
            name: 'ClosedDateUtc',
            type: 'timestamp',
            required: false,
          },
        ],
      },
    ],
  },
  'ppm.finalizations': {
    description:
      'Completes or cancels programs and closes or archives portfolios, after their contents have been imported.',
    files: [
      {
        field: 'file',
        required: true,
        columns: [
          {
            name: 'ImportId',
            type: 'text',
            required: false,
            description:
              "The caller's own key for this row, unique within the file (case-insensitively). Results are reported against it. Falls back to the row's position when the column is absent, so a hand-authored file still works.",
          },
          {
            name: 'Type',
            type: 'text',
            required: true,
            values: ['Program', 'Portfolio'],
          },
          {
            name: 'Id',
            type: 'id',
            required: true,
            description: 'The program or portfolio this row closes, per Type.',
          },
          {
            name: 'Status',
            type: 'text',
            required: true,
            description:
              "Programs: 'Completed' or 'Canceled'. Portfolios: 'Closed' or 'Archived'.",
            values: ['Completed', 'Canceled', 'Closed', 'Archived'],
          },
          {
            name: 'EndDate',
            type: 'date',
            required: false,
            description:
              "The portfolio's end date. Required for portfolio rows, ignored for program rows.",
          },
        ],
      },
    ],
  },
  'ppm.portfolios': {
    files: [
      {
        field: 'file',
        required: true,
        columns: [
          {
            name: 'ImportId',
            type: 'text',
            required: false,
            description:
              "The caller's own key for this row, unique within the file (case-insensitively). Results are reported against it. Falls back to the row's position when the column is absent, so a hand-authored file still works.",
          },
          {
            name: 'Name',
            type: 'text',
            required: true,
            maxLength: 128,
          },
          {
            name: 'Description',
            type: 'text',
            required: true,
            maxLength: 1024,
          },
          {
            name: 'Status',
            type: 'text',
            required: true,
            description:
              "The portfolio's status. Defaults to Active when the column is absent.",
            values: ['Proposed', 'Active', 'OnHold', 'Closed', 'Archived'],
          },
          {
            name: 'CreatedOn',
            type: 'date',
            required: true,
            description:
              'The date the portfolio was proposed. Required on every row. Nothing stores it yet — a portfolio keeps no creation date beyond the audit stamp, which records when the file was uploaded — but the column is required now so that no file has to change on the day one is kept.',
          },
          {
            name: 'ActivatedOn',
            type: 'date',
            required: false,
            description:
              'The date the portfolio was activated. Required unless the portfolio is Proposed. There is no closing date here: an import cannot close a portfolio, so the finalize import carries that one.',
          },
          {
            name: 'Sponsors',
            type: 'text',
            required: false,
          },
          {
            name: 'Owners',
            type: 'text',
            required: false,
          },
          {
            name: 'Managers',
            type: 'text',
            required: false,
          },
        ],
      },
    ],
  },
  'ppm.programs': {
    files: [
      {
        field: 'file',
        required: true,
        columns: [
          {
            name: 'ImportId',
            type: 'text',
            required: false,
            description:
              "The caller's own key for this row, unique within the file (case-insensitively). Results are reported against it. Falls back to the row's position when the column is absent, so a hand-authored file still works.",
          },
          {
            name: 'Name',
            type: 'text',
            required: true,
            maxLength: 128,
          },
          {
            name: 'Description',
            type: 'text',
            required: true,
            maxLength: 2048,
          },
          {
            name: 'PortfolioId',
            type: 'id',
            required: true,
          },
          {
            name: 'Status',
            type: 'text',
            required: true,
            description:
              "The program's status. Defaults to Active when the column is absent.",
            values: ['Proposed', 'Active', 'Completed', 'Canceled'],
          },
          {
            name: 'Start',
            type: 'date',
            required: false,
            description: 'The timeline the program plans to run over.',
          },
          {
            name: 'End',
            type: 'date',
            required: false,
          },
          {
            name: 'CreatedOn',
            type: 'date',
            required: true,
            description:
              'The date the program was proposed. Required on every row. Nothing stores it yet — a program keeps no transition dates beyond the audit stamp, which records when the file was uploaded — but the column is required now so that no file has to change on the day one is kept.',
          },
          {
            name: 'ActivatedOn',
            type: 'date',
            required: false,
            description:
              'The date the program became active. Required once the status is Active or Completed, optional on a canceled program, and rejected on one that never got that far. There is no closing date here: an import cannot complete or cancel a program, so the finalize import carries that one.',
          },
          {
            name: 'StrategicThemes',
            type: 'text',
            required: false,
            description: 'Semicolon-separated strategic theme ids.',
          },
          {
            name: 'Sponsors',
            type: 'text',
            required: false,
          },
          {
            name: 'Owners',
            type: 'text',
            required: false,
          },
          {
            name: 'Managers',
            type: 'text',
            required: false,
          },
        ],
      },
    ],
  },
  'ppm.project-stages': {
    description:
      'Each row names the project and stage it sets, so one file can cover many projects.',
    files: [
      {
        field: 'file',
        required: true,
        columns: [
          {
            name: 'ImportId',
            type: 'text',
            required: false,
            description:
              "The caller's own key for this row, unique within the file (case-insensitively). Results are reported against it. Falls back to the row's position when the column is absent, so a hand-authored file still works.",
          },
          {
            name: 'ProjectKey',
            type: 'text',
            required: true,
          },
          {
            name: 'StageName',
            type: 'text',
            required: true,
          },
          {
            name: 'Status',
            type: 'text',
            required: true,
            description:
              "The stage status (case-insensitive): 'NotStarted', 'InProgress', 'Completed' or 'Canceled'.",
            values: ['NotStarted', 'InProgress', 'Completed', 'Canceled'],
          },
        ],
      },
    ],
  },
  'ppm.project-tasks': {
    description:
      'Each row names the project it belongs to, so one file can cover many projects.',
    files: [
      {
        field: 'file',
        required: true,
        columns: [
          {
            name: 'ImportId',
            type: 'text',
            required: false,
            description:
              "The caller's own key for this row, unique within the file (case-insensitively). Results are reported against it, and child rows name it as their ParentImportId. Falls back to the row's position when the column is absent, so a hand-authored file still works.",
          },
          {
            name: 'ProjectKey',
            type: 'text',
            required: true,
          },
          {
            name: 'Name',
            type: 'text',
            required: true,
            maxLength: 128,
          },
          {
            name: 'Description',
            type: 'text',
            required: false,
            maxLength: 2048,
          },
          {
            name: 'StageName',
            type: 'text',
            required: true,
          },
          {
            name: 'ParentImportId',
            type: 'text',
            required: false,
            description:
              'The ImportId of the row this task nests under. Empty makes it a root task of its stage.',
          },
          {
            name: 'ParentTaskId',
            type: 'id',
            required: false,
            description:
              'The id of an existing task this one nests under. Cannot be combined with ParentImportId.',
          },
          {
            name: 'Type',
            type: 'text',
            required: true,
            description:
              "'Task' or 'Milestone'. Defaults to Task when the column is absent.",
            values: ['Task', 'Milestone'],
          },
          {
            name: 'Status',
            type: 'text',
            required: true,
            values: ['NotStarted', 'InProgress', 'Completed', 'Canceled'],
          },
          {
            name: 'Priority',
            type: 'text',
            required: true,
            values: ['Low', 'Medium', 'High', 'Critical'],
          },
          {
            name: 'Progress',
            type: 'number',
            required: false,
            description:
              'Percent complete (0-100). Required for tasks, not allowed for milestones.',
          },
          {
            name: 'PlannedStart',
            type: 'date',
            required: false,
            description:
              'Planned start, for tasks. Milestones use PlannedDate instead.',
          },
          {
            name: 'PlannedEnd',
            type: 'date',
            required: false,
          },
          {
            name: 'PlannedDate',
            type: 'date',
            required: false,
            description: "The milestone's date. Only for milestones.",
          },
          {
            name: 'EstimatedEffortHours',
            type: 'number',
            required: false,
          },
          {
            name: 'Assignees',
            type: 'text',
            required: false,
            description:
              'Semicolon-separated employee numbers assigned to the task.',
          },
        ],
      },
    ],
  },
  'ppm.projects': {
    files: [
      {
        field: 'file',
        required: true,
        columns: [
          {
            name: 'ImportId',
            type: 'text',
            required: false,
            description:
              "The caller's own key for this row, unique within the file (case-insensitively). Results are reported against it. Falls back to the row's position when the column is absent, so a hand-authored file still works.",
          },
          {
            name: 'Name',
            type: 'text',
            required: true,
            maxLength: 128,
          },
          {
            name: 'Description',
            type: 'text',
            required: true,
            maxLength: 4096,
          },
          {
            name: 'Key',
            type: 'text',
            required: true,
          },
          {
            name: 'PortfolioId',
            type: 'id',
            required: true,
          },
          {
            name: 'ExpenditureCategoryId',
            type: 'integer',
            required: true,
          },
          {
            name: 'Status',
            type: 'text',
            required: true,
            description:
              "The project's status. Defaults to Active when the column is absent.",
            values: ['Proposed', 'Active', 'Completed', 'Canceled', 'Approved'],
          },
          {
            name: 'ProgramId',
            type: 'id',
            required: false,
            description:
              'The program this project belongs to, if any. The program must be in the same portfolio.',
          },
          {
            name: 'ProjectLifecycleId',
            type: 'id',
            required: false,
            description:
              'The lifecycle to assign. Required for approved projects, and by any project with tasks.',
          },
          {
            name: 'BusinessCase',
            type: 'text',
            required: false,
            maxLength: 4096,
          },
          {
            name: 'ExpectedBenefits',
            type: 'text',
            required: false,
            maxLength: 4096,
          },
          {
            name: 'Start',
            type: 'date',
            required: false,
            description: 'The timeline the project plans to run over.',
          },
          {
            name: 'End',
            type: 'date',
            required: false,
          },
          {
            name: 'CreatedOn',
            type: 'date',
            required: true,
            description:
              "The date the project was proposed. Required on every row, and what the project's opening status history entry is dated — the audit stamp records when the file was uploaded, which is not the same thing.",
          },
          {
            name: 'ActivatedOn',
            type: 'date',
            required: false,
            description:
              'The date the project became active. Required once the status is Active or Completed, optional on a canceled project, and rejected on one that never got that far.',
          },
          {
            name: 'ClosedOn',
            type: 'date',
            required: false,
            description:
              'The date the project was completed or canceled — the status says which. Required on those two statuses and rejected on the rest.',
          },
          {
            name: 'StrategicThemes',
            type: 'text',
            required: false,
            description: 'Semicolon-separated strategic theme ids.',
          },
          {
            name: 'Sponsors',
            type: 'text',
            required: false,
          },
          {
            name: 'Owners',
            type: 'text',
            required: false,
          },
          {
            name: 'Managers',
            type: 'text',
            required: false,
          },
          {
            name: 'Members',
            type: 'text',
            required: false,
          },
        ],
      },
    ],
  },
  'ppm.strategic-initiatives': {
    description:
      'Optionally accepts a second csv of KPIs, whose rows name the ImportId of the initiative they belong to.',
    files: [
      {
        field: 'file',
        required: true,
        columns: [
          {
            name: 'ImportId',
            type: 'text',
            required: false,
            description:
              "The caller's own key for this row, unique within the file (case-insensitively). Results are reported against it, and the KPI file names it to say which initiative a KPI belongs to. Falls back to the row's position when the column is absent, so a hand-authored file still works.",
          },
          {
            name: 'Name',
            type: 'text',
            required: true,
            maxLength: 128,
          },
          {
            name: 'Description',
            type: 'text',
            required: true,
            maxLength: 2048,
          },
          {
            name: 'PortfolioId',
            type: 'id',
            required: true,
          },
          {
            name: 'Status',
            type: 'text',
            required: true,
            description:
              "The initiative's status. Defaults to Active when the column is absent.",
            values: [
              'Proposed',
              'Approved',
              'Active',
              'OnHold',
              'Completed',
              'Canceled',
            ],
          },
          {
            name: 'Start',
            type: 'date',
            required: true,
          },
          {
            name: 'End',
            type: 'date',
            required: true,
          },
          {
            name: 'ProjectKeys',
            type: 'text',
            required: false,
            description:
              'Semicolon-separated project keys the initiative delivers through.',
          },
          {
            name: 'Sponsors',
            type: 'text',
            required: false,
          },
          {
            name: 'Owners',
            type: 'text',
            required: false,
          },
        ],
      },
      {
        field: 'kpiFile',
        label: 'KPIs',
        required: false,
        columns: [
          {
            name: 'StrategicInitiativeImportId',
            type: 'text',
            required: true,
            description:
              'The ImportId of the initiative row this KPI belongs to. Where that row left the column blank its position stands in, so 1 reaches the first initiative — but a file carrying KPIs should supply ImportId, since inserting a row silently re-parents every KPI below it.',
          },
          {
            name: 'Name',
            type: 'text',
            required: true,
            maxLength: 64,
          },
          {
            name: 'Description',
            type: 'text',
            required: false,
            maxLength: 512,
          },
          {
            name: 'TargetValue',
            type: 'number',
            required: true,
          },
          {
            name: 'StartingValue',
            type: 'number',
            required: false,
          },
          {
            name: 'Prefix',
            type: 'text',
            required: false,
            description: 'A symbol shown before the value, such as "$".',
            maxLength: 8,
          },
          {
            name: 'Suffix',
            type: 'text',
            required: false,
            description: 'A symbol shown after the value, such as "%".',
            maxLength: 8,
          },
          {
            name: 'TargetDirection',
            type: 'text',
            required: true,
            description:
              'Whether success means increasing or decreasing the value. Defaults to Increase.',
            values: ['Increase', 'Decrease'],
          },
        ],
      },
    ],
  },
  'product-management.deployment-environments': {
    description:
      "Each row is created active unless IsActive is false, in which case it is created and then retired — for the environments a historical backfill's deployments still point at.",
    files: [
      {
        field: 'file',
        required: true,
        columns: [
          {
            name: 'ImportId',
            type: 'text',
            required: false,
            description:
              "The caller's own key for this row, unique within the file (case-insensitively). Results are reported against it. Falls back to the row's position when the column is absent, so a hand-authored file still works.",
          },
          {
            name: 'Name',
            type: 'text',
            required: true,
            description:
              'What your organization calls it — "Production", "prod-eu", "QA2".',
            maxLength: 64,
          },
          {
            name: 'Category',
            type: 'text',
            required: true,
            description:
              'Development, Testing, Staging or Production, case-insensitively.',
            values: ['Development', 'Testing', 'Staging', 'Production'],
          },
          {
            name: 'RingOrder',
            type: 'integer',
            required: true,
            description: 'Position in a progressive rollout, lowest first.',
          },
          {
            name: 'IsActive',
            type: 'boolean',
            required: false,
            description:
              "Whether the environment is still deployed into. Blank means active; false creates it and then retires it, for the environments a historical backfill's deployments still point at.",
          },
        ],
      },
    ],
  },
  'product-management.deployments': {
    description:
      'Each row names its version or package by id and its environment by name, and is walked to the outcome it describes with the timestamps it carries: no outcome leaves it in flight, Succeeded and Failed complete it, and RolledBack records a success and then the rollback. A build number is never resolved to a version.',
    files: [
      {
        field: 'file',
        required: true,
        columns: [
          {
            name: 'ImportId',
            type: 'text',
            required: false,
            description:
              "The caller's own key for this row, unique within the file (case-insensitively). Results are reported against it. Falls back to the row's position when the column is absent, so a hand-authored file still works.",
          },
          {
            name: 'VersionId',
            type: 'id',
            required: false,
            description:
              'The version deployed, by id. Leave empty when a package was deployed.',
          },
          {
            name: 'PackageId',
            type: 'id',
            required: false,
            description:
              'The package deployed, by id. Leave empty when a version was deployed.',
          },
          {
            name: 'EnvironmentName',
            type: 'text',
            required: true,
            description: 'The environment reached, by name.',
            maxLength: 64,
          },
          {
            name: 'ArtifactId',
            type: 'text',
            required: false,
            description:
              'The build that actually shipped — 4.8.2.008 where the version number is 4.8.2.',
            maxLength: 128,
          },
          {
            name: 'StartedAt',
            type: 'text',
            required: true,
            description: 'When the deployment began, with its offset.',
          },
          {
            name: 'Outcome',
            type: 'text',
            required: false,
            description:
              'Succeeded, Failed or RolledBack, case-insensitively. Blank leaves the deployment in flight.',
            values: ['Succeeded', 'Failed', 'RolledBack'],
          },
          {
            name: 'CompletedAt',
            type: 'text',
            required: true,
            description:
              'When the deployment reached its outcome, with its offset. Required with an outcome. For a rollback, when it succeeded.',
          },
          {
            name: 'RolledBackAt',
            type: 'text',
            required: true,
            description:
              'When a rolled-back deployment was reverted, with its offset. Required for a rollback.',
          },
          {
            name: 'Reason',
            type: 'text',
            required: false,
            description: 'Why it failed or was rolled back. Max 1024 chars.',
            maxLength: 1024,
          },
        ],
      },
    ],
  },
  'product-management.products': {
    files: [
      {
        field: 'file',
        required: true,
        columns: [
          {
            name: 'ImportId',
            type: 'text',
            required: false,
            description:
              "The caller's own key for this row, unique within the file (case-insensitively). Results are reported against it, and child rows name it as their ParentImportId. Falls back to the row's position when the column is absent — but a file with parents should supply it, since a position is a fragile thing to reference.",
          },
          {
            name: 'Name',
            type: 'text',
            required: true,
            maxLength: 128,
          },
          {
            name: 'Description',
            type: 'text',
            required: false,
            maxLength: 1024,
          },
          {
            name: 'ProductTypeName',
            type: 'text',
            required: true,
            description:
              'The product type by name, which must already exist and be active.',
          },
          {
            name: 'ParentImportId',
            type: 'text',
            required: false,
            description:
              'The ImportId of another row in this file, or empty for a root product.',
          },
          {
            name: 'ExternalId',
            type: 'text',
            required: false,
            maxLength: 256,
          },
          {
            name: 'Status',
            type: 'text',
            required: false,
            description:
              "The status by name, which must belong to the product workflow. Defaults to the workflow's initial status when the column is absent or blank.",
          },
          {
            name: 'Tags',
            type: 'text',
            required: false,
            description:
              "The product's tags, as semicolon-separated Category|Tag pairs — Platform|ios;Platform|android;Compliance|pci-scope.",
          },
        ],
      },
    ],
  },
  'product-management.release-packages': {
    description:
      'Takes two files: one row per package, and one row per manifest line naming the ImportId of the package it belongs to. Both are required — a package cannot be assembled without a manifest.',
    files: [
      {
        field: 'file',
        required: true,
        columns: [
          {
            name: 'ImportId',
            type: 'text',
            required: false,
            description:
              "The caller's own key for this row, unique within the file (case-insensitively). Results are reported against it, and the manifest file names it to say which package a line belongs to. Falls back to the row's position when the column is absent.",
          },
          {
            name: 'Version',
            type: 'text',
            required: true,
            description:
              "The package's own version, distinct from any component's. Free text, never parsed.",
            maxLength: 64,
          },
          {
            name: 'Name',
            type: 'text',
            required: false,
            maxLength: 128,
          },
          {
            name: 'TargetDate',
            type: 'date',
            required: false,
          },
          {
            name: 'ReleasedDate',
            type: 'date',
            required: false,
            description:
              'When the package shipped. Supplying it makes the package Released.',
          },
        ],
      },
      {
        field: 'manifestFile',
        label: 'Manifest',
        required: true,
        columns: [
          {
            name: 'PackageImportId',
            type: 'text',
            required: true,
            description:
              'The `ImportId` of the package row this line belongs to.',
          },
          {
            name: 'ProductId',
            type: 'id',
            required: true,
            description: 'The component product, by id.',
          },
          {
            name: 'VersionNumber',
            type: 'text',
            required: true,
            description:
              "The component's version in this package. Free text, never parsed.",
            maxLength: 64,
          },
          {
            name: 'Kind',
            type: 'text',
            required: true,
            description:
              'Whether the component changed in this package. `Changed` or `CarriedForward`.',
            values: ['Changed', 'CarriedForward'],
          },
        ],
      },
    ],
  },
  'product-management.releases': {
    description:
      'Takes two files: one row per release, and one row per thing it announces, naming the ImportId of the release it belongs to. The contents file is optional — an empty release is a legitimate state. A release marked released is refused while anything it carries has not shipped.',
    files: [
      {
        field: 'file',
        required: true,
        columns: [
          {
            name: 'ImportId',
            type: 'text',
            required: false,
            description:
              "The caller's own key for this row, unique within the file (case-insensitively). Results are reported against it, and the contents file names it to say which release a row belongs to. Falls back to the row's position when the column is absent.",
          },
          {
            name: 'Version',
            type: 'text',
            required: true,
            description:
              'The release as the organization announces it — `2026.07`. Free text, never parsed.',
            maxLength: 64,
          },
          {
            name: 'Name',
            type: 'text',
            required: false,
            maxLength: 128,
          },
          {
            name: 'ProductId',
            type: 'id',
            required: false,
            description:
              'The product this release is announced under, if any, by id. Usually a product line.',
          },
          {
            name: 'TargetDate',
            type: 'date',
            required: false,
          },
          {
            name: 'ReleasedDate',
            type: 'date',
            required: false,
            description:
              'When it was announced. Supplying it makes the release Released — and is refused while anything it carries has not shipped.',
          },
          {
            name: 'Sequence',
            type: 'integer',
            required: false,
          },
          {
            name: 'Notes',
            type: 'text',
            required: false,
            description:
              'Product notes for this release, written for customers.',
          },
        ],
      },
      {
        field: 'contentsFile',
        label: 'Contents',
        required: false,
        columns: [
          {
            name: 'ReleaseImportId',
            type: 'text',
            required: true,
            description:
              'The `ImportId` of the release row this row belongs to.',
          },
          {
            name: 'Kind',
            type: 'text',
            required: true,
            description: '`Package` or `Version`.',
            values: ['Package', 'Version'],
          },
          {
            name: 'PackageId',
            type: 'id',
            required: true,
            description: 'The package, by id. Required when Kind is `Package`.',
          },
          {
            name: 'VersionId',
            type: 'id',
            required: true,
            description: 'The version, by id. Required when Kind is `Version`.',
          },
        ],
      },
    ],
  },
  'product-management.versions': {
    description:
      'Each row is planned against its product by id and walked to the state its dates describe: no dates leaves it planned, a cut date makes it ready, a released date makes it released.',
    files: [
      {
        field: 'file',
        required: true,
        columns: [
          {
            name: 'ImportId',
            type: 'text',
            required: false,
            description:
              "The caller's own key for this row, unique within the file (case-insensitively). Results are reported against it. Falls back to the row's position when the column is absent, so a hand-authored file still works.",
          },
          {
            name: 'ProductId',
            type: 'id',
            required: true,
            description:
              'The product this version was cut against, by id. Must be a releasable type.',
          },
          {
            name: 'Number',
            type: 'text',
            required: true,
            description:
              'The version as the organization writes it. Free text, never parsed.',
            maxLength: 64,
          },
          {
            name: 'Name',
            type: 'text',
            required: false,
            maxLength: 128,
          },
          {
            name: 'TargetDate',
            type: 'date',
            required: false,
          },
          {
            name: 'CutDate',
            type: 'date',
            required: false,
            description:
              'When scope froze. Supplying it makes the version Ready.',
          },
          {
            name: 'ReleasedDate',
            type: 'date',
            required: false,
            description:
              'When it shipped. Supplying it makes the version Released.',
          },
          {
            name: 'Sequence',
            type: 'integer',
            required: false,
            description:
              'A manual ordering override, for the rare case where chronology misleads.',
          },
          {
            name: 'Notes',
            type: 'text',
            required: false,
            description: 'Engineering notes for this version.',
          },
        ],
      },
    ],
  },
  'strategic.themes': {
    files: [
      {
        field: 'file',
        required: true,
        columns: [
          {
            name: 'ImportId',
            type: 'text',
            required: false,
            description:
              "The caller's own key for this row, unique within the file (case-insensitively). Results are reported against it. Falls back to the row's position when the column is absent, so a hand-authored file still works.",
          },
          {
            name: 'Name',
            type: 'text',
            required: true,
            maxLength: 64,
          },
          {
            name: 'Description',
            type: 'text',
            required: true,
            maxLength: 1024,
          },
          {
            name: 'State',
            type: 'text',
            required: true,
            description:
              "The theme's state. Defaults to Active when the column is absent.",
            values: ['Proposed', 'Active', 'Archived'],
          },
        ],
      },
    ],
  },
  'team-members': {
    files: [
      {
        field: 'file',
        required: true,
        columns: [
          {
            name: 'ImportId',
            type: 'text',
            required: false,
            description:
              "The caller's own key for this row, unique within the file (case-insensitively). Results are reported against it. Falls back to the row's position when the column is absent, so a hand-authored file still works.",
          },
          {
            name: 'TeamCode',
            type: 'text',
            required: true,
            maxLength: 10,
          },
          {
            name: 'EmployeeNumber',
            type: 'text',
            required: true,
            maxLength: 256,
          },
          {
            name: 'RoleName',
            type: 'text',
            required: true,
            maxLength: 128,
          },
        ],
      },
    ],
  },
  'team-memberships': {
    files: [
      {
        field: 'file',
        required: true,
        columns: [
          {
            name: 'ImportId',
            type: 'text',
            required: false,
            description:
              "The caller's own key for this row, unique within the file (case-insensitively). Results are reported against it. Falls back to the row's position when the column is absent, so a hand-authored file still works.",
          },
          {
            name: 'ChildCode',
            type: 'text',
            required: true,
            maxLength: 10,
          },
          {
            name: 'ParentCode',
            type: 'text',
            required: true,
            maxLength: 10,
          },
          {
            name: 'Start',
            type: 'date',
            required: true,
          },
          {
            name: 'End',
            type: 'date',
            required: false,
          },
        ],
      },
    ],
  },
  teams: {
    files: [
      {
        field: 'file',
        required: true,
        columns: [
          {
            name: 'ImportId',
            type: 'text',
            required: false,
            description:
              "The caller's own key for this row, unique within the file (case-insensitively). Results are reported against it. Falls back to the row's position when the column is absent, so a hand-authored file still works.",
          },
          {
            name: 'Type',
            type: 'text',
            required: true,
            values: ['Team', 'TeamOfTeams'],
          },
          {
            name: 'Name',
            type: 'text',
            required: true,
            maxLength: 128,
          },
          {
            name: 'Code',
            type: 'text',
            required: true,
            maxLength: 10,
          },
          {
            name: 'Description',
            type: 'text',
            required: false,
            maxLength: 1024,
          },
          {
            name: 'ActiveDate',
            type: 'date',
            required: true,
          },
          {
            name: 'IsActive',
            type: 'boolean',
            required: true,
            description:
              'Whether the team is currently active. Defaults to true when the column is absent.',
          },
          {
            name: 'InactiveDate',
            type: 'date',
            required: false,
            description:
              'When the team was retired. Required when IsActive is false; must be after ActiveDate.',
          },
        ],
      },
    ],
  },
} as const satisfies Record<string, ImportTemplate>

export type ImportKey = keyof typeof importTemplates
