<Project Sdk="Microsoft.NET.Sdk">

    <ItemGroup>
        <PackageReference Include="CSharpFunctionalExtensions" />
        <PackageReference Include="FluentValidation" />
        <PackageReference Include="NCalc.Core" />
        <PackageReference Include="NodaTime" />
        <PackageReference Include="NodaTime.Serialization.SystemTextJson" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\Wayd.Common\Wayd.Common.csproj" />
    </ItemGroup>

</Project>
