<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <IsPackable>false</IsPackable>
        <IsTestProject>true</IsTestProject>
        <OutputType>Exe</OutputType>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="FluentAssertions" />
        <PackageReference Include="xunit.v3" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\..\..\Wayd.Common\src\Wayd.Common.Domain\Wayd.Common.Domain.csproj" />
        <ProjectReference Include="..\..\..\..\Wayd.Common\tests\Wayd.Tests.Shared\Wayd.Tests.Shared.csproj" />
        <ProjectReference Include="..\..\src\Wayd.Planning.Application\Wayd.Planning.Application.csproj" />
        <ProjectReference Include="..\..\src\Wayd.Planning.Domain\Wayd.Planning.Domain.csproj" />
        <ProjectReference Include="..\Wayd.Planning.Domain.Tests\Wayd.Planning.Domain.Tests.csproj" />
    </ItemGroup>

</Project>
